### PR TITLE
Add rbenv support to the Ruby switch command

### PR DESCRIPTION
**Pull request by BytesGuy**
Future macOS images will migrate to rbenv from chruby to help align our software offering across our VM images.

This PR adds support for rbenv to the ruby switch command with the intention of being a minor patch release to the macOS orb. As we recommend in the docs pinning the macOS orb to `@2`, this should be a transparent update once the macOS images are switched to rbenv as the same config will work.

Also added is fuzzy version matching. Rbenv has historically pushed back against having this, but we can work around this with some bash. The motivation here is to match chruby as it is common to only supply the major.minor version for the requested ruby. This maintains backwards compatibility with configs that have not been updated. e.g.,

```
  - macos/switch-ruby:
      version: "3.0"
```

This would normally fail under rbenv as the patch version was not supplied, but with the additional fuzzy matching this will resolve to the version of ruby 3.0 that is installed in the image.

### CODE REVIEW

**Review by EricRibeiro — APPROVED** [review]
LGTM

**Review by fritz-circleci — APPROVED** [review]

**Review by michael-webster — COMMENTED** [review]
@BytesGuy can you clarify this for me:

> This maintains backwards compatibility with configs that have not been updated

I'm not sure what the backwards compatibility question is. My understanding is that customers who don't update their configs will just stay on the old orb behavior. Or is there something else I am missing?

**Review by z00b — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:0f880ad883eeeae6ed1a3a8780b05d07d6edb8a6

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=2.3.3

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:0f880ad883eeeae6ed1a3a8780b05d07d6edb8a6

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:0f880ad883eeeae6ed1a3a8780b05d07d6edb8a6

**Pull request merged**
