### PR TITLE
Adds additional description for `enable-vnc`.

### PR DESCRIPTION
**Pull request by alanjclark**
Added short description of the use of the `enable-vnc` command and how to connect to the VM afterwards.

### CODE REVIEW

**Review by BytesGuy — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:a96f5f8e97205498c373776e97c440742a4128e4

**Review by felicianotech — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:91a4055bcd23413d1b883414316e2cb7cbf20801

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:91a4055bcd23413d1b883414316e2cb7cbf20801

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=2.3.2

**Pull request merged**
