### PR TITLE
[CPE-1524] Add install Rosetta command

### PR DESCRIPTION
**Pull request by BytesGuy**
This command allows installation of Rosetta 2 for Apple Silicon executors

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:a93996cb073eb85e2c2d98d73bc5e7131f57d5f4

**Review by JalexChen — APPROVED** [review]

**Review by EricRibeiro — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:0044eb7068231367fc99627e19f04011f9be3077

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=dev:0044eb7068231367fc99627e19f04011f9be3077

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/macos?version=2.3.4

**Pull request merged**
